language: python
addons:
  postgresql: "9.3"
env:
  PYTHONPATH='.'
install: "pip install -r requirements-dev.txt"
before_script:
  - psql -U postgres -c 'CREATE DATABASE tx_lobbying;'
  - psql -U postgres -c "CREATE EXTENSION postgis" -d tx_lobbying
  - psql -U postgres -c "CREATE EXTENSION postgis_topology" -d tx_lobbying
script: make test
